"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { otpSchema, phoneSchema } from "@/lib/auth/schemas";
import {
  sendBusinessSms,
  sendBusinessWhatsApp,
  sendSms,
} from "@/lib/notify";
import { sms } from "@/lib/notify/templates";
import { getPlanStatus } from "@/lib/plan/enforce";
import {
  cancelAppointmentByIdAsOwner,
  cancelAppointmentByToken,
  createBookingForBusiness,
} from "@/lib/db/appointments";
import {
  getBusinessForNotifyById,
  getCurrentBusiness,
  getPublicBusinessBySlug,
} from "@/lib/db/businesses";
import { createOtp, generateOtp, verifyOtpById } from "@/lib/db/otp";
import {
  generateSlotsForDate,
  takenByDate,
} from "@/lib/appointments/slots";
import { getTakenByDateForSlug } from "@/lib/db/appointments";
import type { PendingBookingMetadata } from "./types";

export type ActionResult<T = unknown> =
  | { ok: true; data?: T }
  | { ok: false; error: string };

// ────────────────────────────────────────────────────────────
// createBooking (customer → server): store pending OTP + SMS
// ────────────────────────────────────────────────────────────
const createSchema = z.object({
  slug: z.string().min(1),
  ad_soyad: z.string().trim().min(2, "Adını gir."),
  telefon: phoneSchema,
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Geçerli bir tarih seç."),
  time: z.string().regex(/^\d{2}:\d{2}$/, "Geçerli bir saat seç."),
});

export async function createBookingAction(
  input: unknown,
): Promise<ActionResult<{ pendingId: string }>> {
  const parsed = createSchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      error: parsed.error.issues[0]?.message ?? "Form geçersiz.",
    };
  }
  const { slug, ad_soyad, telefon, date, time } = parsed.data;

  // Need the full record (with telefon for owner notification) — use service role.
  const business = await getBusinessForNotifyBySlugServerSide(slug);
  if (!business) return { ok: false, error: "Firma bulunamadı." };

  // Plan quota — block the booking on Free if the monthly cap is hit.
  const planStatus = await getPlanStatus(business.id);
  if (!planStatus.canAcceptBooking) {
    return {
      ok: false,
      error: "Bu firma şu an yeni randevu kabul edemiyor. Lütfen sonra tekrar dene.",
    };
  }

  // Verify slot is generated by current working hours + slot config
  const takenMap = await getTakenByDateForSlug(slug);
  const slots = generateSlotsForDate(
    { ...business, telefon: "", email: "" },
    date,
    takenMap[date] ?? [],
  );
  if (!slots.includes(time)) {
    return { ok: false, error: "Bu saat artık dolu, başka bir saat seç." };
  }

  const otp = generateOtp();
  const metadata: PendingBookingMetadata = {
    business_id: business.id,
    business_name: business.ad_soyad,
    business_phone: business.telefon,
    customer_name: ad_soyad,
    customer_phone: telefon,
    date,
    time,
  };

  let pendingId: string;
  try {
    const result = await createOtp({
      telefon,
      code: otp,
      amac: "booking",
      metadata: metadata as unknown as Record<string, unknown>,
    });
    pendingId = result.id;
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : "OTP oluşturulamadı.",
    };
  }

  await sendSms({
    to: telefon,
    tag: "booking-otp",
    message: sms.bookingOtp(business.ad_soyad, otp),
  });

  return { ok: true, data: { pendingId } };
}

// helper that re-exports the admin lookup to avoid a circular import header
async function getBusinessForNotifyBySlugServerSide(slug: string) {
  const { getBusinessForNotifyBySlug } = await import("@/lib/db/businesses");
  return getBusinessForNotifyBySlug(slug);
}

// ────────────────────────────────────────────────────────────
// verifyBookingOtp: confirm slot, create appointment+customer, notify
// ────────────────────────────────────────────────────────────
const verifySchema = z.object({
  pendingId: z.uuid(),
  code: otpSchema,
});

export async function verifyBookingOtpAction(
  input: unknown,
): Promise<
  ActionResult<{
    cancelToken: string;
    businessName: string;
    date: string;
    time: string;
  }>
> {
  const parsed = verifySchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      error: parsed.error.issues[0]?.message ?? "Kod geçersiz.",
    };
  }
  const { pendingId, code } = parsed.data;

  const verify = await verifyOtpById({ id: pendingId, code });
  if (!verify.ok) {
    if (verify.reason === "expired") {
      return { ok: false, error: "Doğrulama süresi doldu. Tekrar dene." };
    }
    if (verify.reason === "mismatch") {
      return { ok: false, error: "Kod yanlış." };
    }
    return { ok: false, error: "Doğrulama kodu bulunamadı." };
  }

  const meta = verify.metadata as PendingBookingMetadata | null;
  if (!meta) return { ok: false, error: "Booking verisi eksik." };

  // Create the appointment + upsert customer atomically.
  const created = await createBookingForBusiness({
    business_id: meta.business_id,
    customer_name: meta.customer_name,
    customer_phone: meta.customer_phone,
    date: meta.date,
    time: meta.time,
    source: "online",
  });
  if (!created.ok) {
    if (created.reason === "slot_taken") {
      return {
        ok: false,
        error: "Bu saat az önce başkası tarafından alındı.",
      };
    }
    return { ok: false, error: created.error ?? "Randevu oluşturulamadı." };
  }

  const appUrl =
    process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  // Customer SMS (business-paid → plan-gated)
  await sendBusinessSms({
    businessId: meta.business_id,
    to: meta.customer_phone,
    tag: "booking-confirmed",
    message: sms.bookingConfirmed({
      businessName: meta.business_name,
      date: meta.date,
      time: meta.time,
      cancelUrl: `${appUrl}/iptal/${created.appointment.cancelToken}`,
    }),
  });

  // Owner WhatsApp (Pro plan only)
  await sendBusinessWhatsApp({
    businessId: meta.business_id,
    to: meta.business_phone,
    template: process.env.WHATSAPP_TEMPLATE_NEW_BOOKING ?? "yeni_randevu",
    variables: {
      customerName: meta.customer_name,
      customerPhone: meta.customer_phone,
      date: meta.date,
      time: meta.time,
    },
  });

  revalidatePath("/app/randevular");
  revalidatePath("/app/musteriler");
  revalidatePath("/app");

  return {
    ok: true,
    data: {
      cancelToken: created.appointment.cancelToken,
      businessName: meta.business_name,
      date: meta.date,
      time: meta.time,
    },
  };
}

// ────────────────────────────────────────────────────────────
// cancelBookingByToken (customer-facing /iptal/[token])
// ────────────────────────────────────────────────────────────
export async function cancelBookingByTokenAction(
  token: string,
): Promise<ActionResult> {
  if (!token || typeof token !== "string") {
    return { ok: false, error: "Geçersiz token." };
  }
  const result = await cancelAppointmentByToken(token);
  if (!result.ok) {
    if (result.reason === "already_cancelled") return { ok: true };
    return { ok: false, error: "Randevu bulunamadı." };
  }

  // Notify the owner via SMS that the customer cancelled.
  const business = await getBusinessForNotifyById(result.business_id);
  if (business) {
    await sendBusinessSms({
      businessId: business.id,
      to: business.telefon,
      tag: "booking-cancelled-owner",
      message: sms.cancelledByCustomer({
        customerName: result.appointment.customerName,
        date: result.appointment.date,
        time: result.appointment.time,
      }),
    });
  }

  revalidatePath("/app/randevular");
  revalidatePath("/app");
  return { ok: true };
}

// ────────────────────────────────────────────────────────────
// cancelAppointment (owner-side, from panel)
// ────────────────────────────────────────────────────────────
export async function cancelAppointmentAction(input: {
  slug?: string;
  id: string;
}): Promise<ActionResult> {
  const business = await getCurrentBusiness();
  if (!business) return { ok: false, error: "Firma bulunamadı." };

  const result = await cancelAppointmentByIdAsOwner(input.id);
  if (!result.ok) return { ok: false, error: "Randevu bulunamadı." };

  await sendBusinessSms({
    businessId: business.id,
    to: result.appointment.customerPhone,
    tag: "booking-cancelled-customer",
    message: sms.cancelledByOwner({
      businessName: business.ad_soyad,
      date: result.appointment.date,
      time: result.appointment.time,
    }),
  });

  revalidatePath("/app/randevular");
  revalidatePath("/app");
  return { ok: true };
}

// ────────────────────────────────────────────────────────────
// createManualAppointment (owner-side, no customer OTP)
// ────────────────────────────────────────────────────────────
const manualSchema = z.object({
  ad_soyad: z.string().trim().min(2, "Müşteri adı en az 2 karakter."),
  telefon: phoneSchema,
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Geçerli bir tarih seç."),
  time: z.string().regex(/^\d{2}:\d{2}$/, "Geçerli bir saat seç."),
  notlar: z.string().optional(),
});

export async function createManualAppointmentAction(
  input: unknown,
): Promise<ActionResult<{ id: string }>> {
  const business = await getCurrentBusiness();
  if (!business) return { ok: false, error: "Firma bulunamadı." };

  // Plan quota
  const planStatus = await getPlanStatus(business.id);
  if (!planStatus.canAcceptBooking) {
    return {
      ok: false,
      error:
        "Bu ayki ücretsiz randevu hakkın doldu. Daha fazlası için Pro'ya geç.",
    };
  }

  const parsed = manualSchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      error: parsed.error.issues[0]?.message ?? "Form geçersiz.",
    };
  }
  const { ad_soyad, telefon, date, time, notlar } = parsed.data;

  const result = await createBookingForBusiness({
    business_id: business.id,
    customer_name: ad_soyad,
    customer_phone: telefon,
    date,
    time,
    notes: notlar,
    source: "manual",
  });
  if (!result.ok) {
    if (result.reason === "slot_taken") {
      return { ok: false, error: "Bu tarih ve saatte zaten randevu var." };
    }
    return { ok: false, error: result.error ?? "Randevu oluşturulamadı." };
  }

  const appUrl =
    process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  await sendBusinessSms({
    businessId: business.id,
    to: telefon,
    tag: "booking-manual",
    message: sms.bookingManual({
      businessName: business.ad_soyad,
      date,
      time,
      cancelUrl: `${appUrl}/iptal/${result.appointment.cancelToken}`,
    }),
  });

  revalidatePath("/app/randevular");
  revalidatePath("/app/musteriler");
  revalidatePath("/app");
  return { ok: true, data: { id: result.appointment.id } };
}

// Re-export helpers used by pages that previously consumed the in-memory
// registry. Internal — kept here so we have one source-of-truth file.
export { takenByDate, getTakenByDateForSlug };
